---
x-env_file: &env_file
  - .env

x-build: &build
  context: .

name: ossi-api

services:
  api-gateway:
    build:
      <<: *build
      dockerfile: ./docker/Dockerfile
      args:
        SERVICE_NAME: api-gateway
    ports:
      - "3000:3000"
    env_file: *env_file
    depends_on:
      - messaging-server
      - student-management-api
      - notification-server
      - auth-api

  auth-api:
    build:
      <<: *build
      dockerfile: ./docker/prismadep.Dockerfile
      args:
        SERVICE_NAME: auth-api
      additional_contexts:
        - prisma-orm=service:db-migrations
    env_file: *env_file
    depends_on:
      - db-migrations

  student-management-api:
    build:
      <<: *build
      dockerfile: ./docker/prismadep.Dockerfile
      args:
        SERVICE_NAME: student-management-api
      additional_contexts:
        - prisma-orm=service:db-migrations
    env_file: *env_file
    depends_on:
      db-migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  notification-server:
    ports:
      - "3001:3000"
    build:
      <<: *build
      dockerfile: ./docker/Dockerfile
      args:
        SERVICE_NAME: notification-server
    env_file: *env_file
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy

  messaging-server:
    build:
      <<: *build
      dockerfile: ./docker/prismadep.Dockerfile
      args:
        SERVICE_NAME: messaging-server
      additional_contexts:
        - prisma-orm=service:db-migrations
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
    env_file: *env_file
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy

  db:
    image: docker.io/postgres:18-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 2s
      retries: 5
      start_period: 1s

  db-migrations:
    extends:
      file: common-services.yml
      service: prisma
    env_file: *env_file
    depends_on:
      db:
        condition: service_healthy
    command: ["npm", "--workspace", "prisma-orm", "run", "start"]

  mongo:
    image: docker.io/mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]

  pgadmin:
    restart: always
    image: docker.io/dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@localhost.fi
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "5433:80"

  redis:
    image: docker.io/redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

volumes:
  db-data:
  mongo-data:
