services:
  api:
    container_name: ossi-api-gateway
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    env_file: ".env"
    depends_on:
      - messagingserver
      - studentmanagementapi
      - notificationserver
      - authapi
  authapi:
    container_name: ossi-auth-api
    build:
      context: ./auth-api
      additional_contexts:
        sequelize-models: ./sequelize-models
    env_file: ".env"
    depends_on:
      - db
  studentmanagementapi:
    container_name: ossi-student-management-api
    build:
      context: ./student-management-api
      additional_contexts:
        sequelize-models: ./sequelize-models
    env_file: ".env"
    depends_on:
      db-migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
  notificationserver:
    container_name: ossi_notification_server
    ports:
      - "3001:3000"
    build:
      context: ./notification-server
    env_file: ".env"
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
  messagingserver:
    build:
      context: ./messaging-server
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
    env_file: ".env"
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
  db:
    container_name: ossi-postgres
    image: docker.io/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ossi-db-data:/var/lib/postgresql/data
    ports:
      - "5442:5442"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 2s
      retries: 5
      start_period: 1s
  db-migrations:
    container_name: ossi-db-migrations
    build:
      context: ./sequelize-models
    depends_on:
      db:
        condition: service_healthy
    command: node migrator up
  mongo:
    image: docker.io/mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
  pgadmin:
    container_name: ossi-pgadmin
    restart: always
    image: docker.io/dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@localhost.fi
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "5433:80"
  redis:
    image: docker.io/redis
    restart: always
    healthcheck:
       test: ["CMD", "redis-cli","ping"]

volumes:
  db-data:
  mongo-data:
