---
services:
  studentmanagementapi:
    build:
      context: ./student-management-api
      target: dev
      additional_contexts:
        prisma-orm: ./prisma-orm
    command: npm run test
    depends_on:
      db-migrations:
        condition: service_completed_successfully
    env_file: ".env"
    volumes:
      - ./student-management-api/src:/usr/server/src:ro
      - ./student-management-api/test:/usr/server/test:ro

  db-test:
    image: docker.io/postgres:18-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-test-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 2s
      retries: 5
      start_period: 1s

  db-migrations:
    build:
      context: ./prisma-orm
    depends_on:
      db-test:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db-test:5432/postgres?schema=public
    command: npm run start:test

volumes:
  db-test-data:
