services:
  api:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    env_file: ".env"
  authapi:
    build:
      context: ./auth-api
    env_file: ".env"
  studentmanagementapi:
    build:
      context: ./student-management-api
    env_file: ".env"
  notificationserver:
    ports:
      - "3001:3000"
    build:
      context: ./notification-server
    env_file: ".env"
  db:
    image: docker.io/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    restart: always
    image: docker.io/dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@localhost.fi
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "5433:80"
  mongo:
    image: docker.io/mongo
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: mongo
volumes:
  db-data:
